# Generated by Django 6.0 on 2025-12-14 21:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CHECK_IN', 'Check in'), ('CHECK_OUT', 'Check out'), ('BREAK_START', 'Break start'), ('BREAK_END', 'Break end')], max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_events', to='core.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_events', to='core.employee')),
            ],
            options={
                'verbose_name': 'Time event',
                'verbose_name_plural': 'Time events',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['employee', 'timestamp'], name='time_tracki_employe_9eac17_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_type', models.CharField(choices=[('WORK', 'Work day'), ('OFF', 'Day off'), ('LEAVE', 'Leave')], default='WORK', max_length=10)),
                ('planned_start', models.TimeField(blank=True, null=True)),
                ('planned_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.employee')),
            ],
            options={
                'verbose_name': 'Work schedule',
                'verbose_name_plural': 'Work schedules',
                'ordering': ['date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
